# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\LowerCASEgui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 1000)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.audioToggleButton = QtWidgets.QPushButton(self.centralwidget)
        self.audioToggleButton.setObjectName("audioToggleButton")
        self.horizontalLayout_3.addWidget(self.audioToggleButton)
        self.highlightErrors = QtWidgets.QPushButton(self.centralwidget)
        self.highlightErrors.setObjectName("highlightErrors")
        self.horizontalLayout_3.addWidget(self.highlightErrors)
        self.revertScript = QtWidgets.QPushButton(self.centralwidget)
        self.revertScript.setObjectName("revertScript")
        self.horizontalLayout_3.addWidget(self.revertScript)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.tempoLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempoLabel.setObjectName("tempoLabel")
        self.horizontalLayout_3.addWidget(self.tempoLabel)
        self.tempoSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.tempoSpinBox.setObjectName("tempoSpinBox")
        self.horizontalLayout_3.addWidget(self.tempoSpinBox)
        spacerItem2 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.masterVolumeLabel = QtWidgets.QLabel(self.centralwidget)
        self.masterVolumeLabel.setObjectName("masterVolumeLabel")
        self.horizontalLayout_3.addWidget(self.masterVolumeLabel)
        self.masterVolumeSlider = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masterVolumeSlider.sizePolicy().hasHeightForWidth())
        self.masterVolumeSlider.setSizePolicy(sizePolicy)
        self.masterVolumeSlider.setMinimumSize(QtCore.QSize(150, 0))
        self.masterVolumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.masterVolumeSlider.setObjectName("masterVolumeSlider")
        self.horizontalLayout_3.addWidget(self.masterVolumeSlider)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scriptPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.scriptPlainTextEdit.setObjectName("scriptPlainTextEdit")
        self.verticalLayout.addWidget(self.scriptPlainTextEdit)
        self.logPlainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logPlainTextEdit.setObjectName("logPlainTextEdit")
        self.verticalLayout.addWidget(self.logPlainTextEdit)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.audioToggleButton.setText(_translate("MainWindow", "Stop Audio"))
        self.highlightErrors.setText(_translate("MainWindow", " Highlight Errors "))
        self.revertScript.setText(_translate("MainWindow", " Revert to most recent valid script... "))
        self.tempoLabel.setText(_translate("MainWindow", "Tempo"))
        self.masterVolumeLabel.setText(_translate("MainWindow", "Master Gain"))
